로컬에서 사용하는 애플리케이션 서버와 테스트에서 같은 데이터베이스를 사용하고 있으니 테스트에서 문제가 발생한다.  
이런 문제를 해결하려면 테스트를 다른 환경과 철저하게 분리해야 한다.

가장 간단한 방법은 테스트 전용 데이터베이스를 별도로 운영하는 것이다.
- H2 데이터베이스를 용도에 따라 두 가지로 구분하면 된다.
	- `jdbc:h2:tcp://localhost/~/test`: local에서 접근하는 서버 전용 데이터베이스
	- `jdbc:h2:tcp://localhost/~/testcase`: test 케이스에서 접근하는 서버 전용 데이터베이스

**데이터베이스 파일 생성 방법**  
- 데이터베이스 서버를 종료하고 다시 실행한다.
- 사용자명은 `sa` 입력
- JDBC URL에 다음 입력
	- `jdbc:h2:~/testcase` (최초 한번)
	- `~/testcase.mv.db` 파일 생성 확인
	- 이후부터는 `jdbc:h2:tcp://localhost/~/testcase` 이렇게 접속

## 테이블 생성
`testcase` 데이터베이스에도 `item` 테이블 생성

```sql
drop table if exists item CASCADE;  
create table item  
(  
    id        bigint generated by default as identity,  
    item_name varchar(10),  
    price     integer,  
    quantity  integer,  
    primary key (id)  
);
```

**접속 정보 변경**  
이제 접속 정보를 변경하자 참고로 `main`에 있는 `application.properties`는 그대로 유지하고, `test`에 있는 `application.properties`만 변경해야 한다.

```
spring.profiles.active=test  
spring.datasource.url=jdbc:h2:tcp://localhost/~/testcase  
spring.datasource.username=sa  
logging.level.org.springframework.jdbc=debug
```

**테스트를 다시 실행**
- `findItems()` 테스트만 단독으로 실행해보자  
- 처음에는 실행에 성공한다.  
- 그런데 같은 `findItems()` 테스트를 다시 실행하면 테스트에 실패한다.
- 테스트를 2번째 실행할 때 실패하는 이유는 `testcase` 데이터베이스에 접속해서 `item` 테이블의 데이터를 확인하면 알 수 있다.
- 처음 테스트를 실행할 때 저장한 데이터가 계속 남아있기 때문에 두 번째 테스트에 영향을 준 것이다.  
- 이 문제는 `save()` 같은 다른 테스트가 먼저 실행되고 나서 `findItems()`를 실행할 때도 나타난다.
	- 다른 테스트에서 이미 데이터를 추가했기 때문이다. 결과적으로 테스트 데이터가 오염된 것이다.
- 이 문제를 해결하려면 각각의 테스트가 끝날 때 마다 해당 테스트에서 추가한 데이터를 삭제해야 한다. 그래야 다른 테스트에 영향을 주지 않는다.

테스트에서 매우 중요한 원칙은 다음과 같다.
- **테스트는 다른 테스트와 격리해야 한다.**
- **테스트는 반복해서 실행할 수 있어야 한다.**

물론 테스트가 끝날 때 마다 추가한 데이터에 `DELETE SQL`을 사용해도 되겠지만, 이 방법도 궁극적인 해결책은 아니다. 
만약 테스트 과정에서 데이터를 이미 추가했는데, 테스트가 실행되는 도중에 예외가 발생하거나 애플리케이션이 종료되어 버려서 테스트 종료 시점에 `DELETE SQL`을 호출하지 못할 수 도 있다.
그러면 결국 데이터가 남아있게 된다.

__출처: 인프런 김영한 지식공유자님의 강의 - 스프링 DB 2편__